name: Terraform Plan

inputs:
  directoy: 
    description: 'Directory to execute terraform (This should also be set in defaults as working directory)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Format
      id: fmt
      run: terraform fmt

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color