on: workflow_dispatch
name: Testing Terraform

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.TF_VAR_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TF_VAR_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TF_VAR_TENANTID }}

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Terraform Plan
        uses: ./actions/TerraformPlan
        with:
          directory: terraform