on: workflow_dispatch
name: Testing Terraform Plan

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Terraform Plan
        uses: ./actions/TerraformPlan
        with:
          directory: terraform
          tf_version: 0.14.8