name: Terrfaform Plan & Apply

on:
  workflow_call:
    inputs:
      terraform_directory:
        required: true
        type: string
      terraform_version:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      ARM_TENANT_ID:
        required: true

  env:
    ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET}}
    ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Show data
        run: |
          echo ${{ inputs.terraform_directory }}
          echo ${{ secrets.ARM_CLIENT_ID}}
          echo ${{ env.ARM_CLIENT_ID}}

      - name: Checkout
        uses: actions/checkout@master

      - name: Terraform Plan
        uses: davidomahony/SharedActions/actions/TerraformPlan@v0.0.1
        with:
          directory: ${{ inputs.terraform_directory }}
          tf_version: ${{ inputs.terraform_version }}

  wait_for_approval:
    name: Waiting for approval
    needs: terraform_plan
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: davidomahony
          minimum-approvals: 1
          issue-title: "Terraform Deployment Approval"
          exclude-workflow-initiator-as-approver: false

  terraform_apply:
    name: Terraform Apply
    needs: wait_for_approval
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Terraform Plan
        uses: davidomahony/SharedActions/actions/TerraformApply@v0.0.1
        with:
          directory: ${{ inputs.terraform_directory }}
          tf_version: ${{ inputs.terraform_version }}