name: Terrfaform Plan & Apply

on:
  workflow_call:
    inputs:
      terraform_directory:
        required: true
        type: string
      terraform_version:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  terraform_plan:
    defaults:
      run:
        working-directory: ${{ inputs.terraform_directory }}

    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      env:
        ARM_CLIENT_ID: ${{ secrets.TF_VAR_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.TF_VAR_CLIENT_SECRET}}
        ARM_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.TF_VAR_TENANTID }}
      run: terraform init


    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true