name: Terrfaform Plan & Apply

on:
  workflow_call:
    inputs:
      terraform_directory:
        required: true
        type: string
      terraform_version:
        required: true
        type: string
      environment:
        required: true
        type: string

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ inputs.terraform_version }}
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: ${{ inputs.terraform_directory }}

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ inputs.terraform_version }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ inputs.terraform_directory }}

      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ inputs.terraform_version }}
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: ${{ inputs.terraform_directory }}

      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ inputs.terraform_version }}
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: ${{ inputs.terraform_directory }}

  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform_plan
    environment: 
      name: dev

    steps:
      - name: Setup Terraform
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ inputs.terraform_version }}
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: ${{ inputs.terraform_directory }}

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ inputs.terraform_version }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ inputs.terraform_directory }}

      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ inputs.terraform_version }}
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: ${{ inputs.terraform_directory }}

      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ inputs.terraform_version }}
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: ${{ inputs.terraform_directory }}

      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ inputs.terraform_version }}
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: ${{ inputs.terraform_directory }}